### ISSUE TITLE
user-agent control in roadtx

### ISSUE THREAD

**Issue by CyrilleFranchet** [dirkjanm/ROADtools#105]
Controlling the User-Agent when using the device code flow could be useful to abuse Conditional Access policies.
What do you think? I can push a PR but should I do it on another function? I identified for my need
- authenticate_device_code_native
- authenticate_device_code_native_v2

but maybe all functions using requests library should handle the UA argument?

**Comment by dirkjanm** [comment]
All auth flows should pass through the `requests_post` [function](https://github.com/dirkjanm/ROADtools/blob/ffb20c506cec9582204a4dba76a4b9f7f69ea170/roadlib/roadtools/roadlib/auth.py#L1459), which automatically changes the user agent if it was set on the command line (should be implemented for all commands in roadtx I think). If it doesn't, let me know.

For the device code flow specifically, I think it takes the platform from the user agent performing the authentication rather than the user agent with which you initialize the flow.
