### ISSUE TITLE
UI performance

### ISSUE THREAD

**Issue by gelim** [dirkjanm/ROADtools#7]
Hey,

regarding to performance on big datasets, I'm doing in `roadtools/roadrecon/server.py`:

``` python
all_foo = db.session.query(Foo).limit(1000).all()
```

and having 1000 in sync with the paging proposed in `foo.component.html`:

``` html
  <mat-paginator [pageSizeOptions]="[50, 100, 500, 1000]"></mat-paginator>
```

(was motived by perf issues mentionned in #6

**Comment by dirkjanm** [comment]
all paging and filtering is currently on client side. You can't page beyond what the server sends, so if the server only queries 1000 records, you can only view 1000 records.
I will need to look at server side paging at some point because this doesn't scale very well for larger environments, but there are quite some hurdles and complexity involved in that. For smaller environments (<50k users) it works reasonably well with client side handling.

**Comment by gelim** [comment]
Yes that's what I realised after :)
So that's solving the perf issue by creating another (partial data available)
I think it's better to close this then.
