### ISSUE TITLE
roadrecon gather segmentation fault

### ISSUE THREAD

**Issue by bill-e-ghote** [dirkjanm/ROADtools#76]
Please advise.

![image](https://github.com/dirkjanm/ROADtools/assets/2491041/34c05d1e-9056-4e13-b80f-534c7854e684)

**Comment by bill-e-ghote** [comment]
Python 3.11.6 within Msys2 running in MINGW64 shell.
$ uname -a
MINGW64_NT-10.0-19045 ETG-HP840-30X0T 3.4.9.x86_64 2023-09-15 12:15 UTC x86_64 Msys

**Comment by bill-e-ghote** [comment]
I tried using going forward.

![image](https://github.com/dirkjanm/ROADtools/assets/2491041/900bc3fa-a453-427e-8e5a-dadc6ff77a4c)

**Comment by bill-e-ghote** [comment]
Not sure these notes will help anyone, but here goes.

Incidentally, I had several issues building from source in this environment. It would not build in Msys2 shell. I had to play tricks to continue past compilation and runtime errors. pyca/cryptography was especially troublesome. The pacman installed version was not being recognized by your apps. 'pip install' would not succeed due to linker errors. I had to build it incrementally from source - I'm not a cmake wizard by any means - but was able to get it past the goalposts. I won't go into those details here as I think it would be more appropriate as an issue on that app's github page. Along the way, I learned way more about rust programming and building than I had intended to pursue.

I also had to work around certificate issues due to our intermediate signer (company internal) not being included in the chain. I appended our signers to certifi/cacert.pem and made sure it was accessible with this:
export SSL_CERT_FILE=/usr/lib/python3.11/site-packages/certifi-2023.7.22-py3.11.egg/certifi/cacert.pem

I initially thought the certificate errors I was seeing was due to my using Burp Suite to debug apps rather than the device certificate, but a little extra reading brought me back on track.

**Comment by dirkjanm** [comment]
Thanks for the detailed information. I don't think there is something I immediately can do about this since you're running it in a bit of an odd environment.

However, as I mentioned previously, the gathering phase was completed before the segmentation fault occured. The line "ROADrecon gather executed in X seconds" is only shown once the entire process is completed. So you should now have the database with all the data and be able to launch the gui, explore the data, run plugins etc.
