### ISSUE TITLE
Can't work with older Db. no such column: Users.onPremisesObjectIdentifier

### ISSUE THREAD

**Issue by ferdinandvroom** [dirkjanm/ROADtools#83]
I needed to analyse a dump from June 2023.

[2024-03-12 17:33:00,209] ERROR in app: Exception on /api/users [GET]
Traceback (most recent call last):
  File "/Users/redacted/Python/roadrecon/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/redacted/Python/roadrecon/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: Users.onPremisesObjectIdentifier

Ferdinand

**Comment by dirkjanm** [comment]
hey Ferdinand,

You would probably have to install a roadlib and roadrecon version from around that time to analyze that dump, preferably in a virtualenv to not modify the system wide install.
The release history is visible on pypi: https://pypi.org/project/roadlib/#history and https://pypi.org/project/roadrecon/#history

So most likely what you'd need is:

```
pip install roadlib==0.18.0 roadrecon==1.1.1
```

These versions were the latest at the time of the dump. Possibly newer versions would work too since the schema was updated in November 2023 with roadlib version 0.20.0.

**Comment by ferdinandvroom** [comment]
> hey Ferdinand,
> 
> You would probably have to install a roadlib and roadrecon version from around that time to analyze that dump, preferably in a virtualenv to not modify the system wide install. The release history is visible on pypi: https://pypi.org/project/roadlib/#history and https://pypi.org/project/roadrecon/#history
> 
> So most likely what you'd need is:
> 
> ```
> pip install roadlib==0.18.0 roadrecon==1.1.1
> ```
> 
> These versions were the latest at the time of the dump. Possibly newer versions would work too since the schema was updated in November 2023 with roadlib version 0.20.0.

Ah! I was looking at the releases on the ROADtools home on Github.
Thanks for the link. It worked fine.

Ferdinand
